language: node_js

node_js:
  - stable

cache:
  directories:
    - 'node-modules'

services:
 - postgresql

before_script:
  - psql -c 'create database questionerdbtest;' -U postgres

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: heroku
  app: questioner-backend
  on:
    repo: dbytecoderc/questioner-backend
    branch: develop
  api_key:
    secure: "637f9376-119e-479f-a450-b273742cda77"